{% set name = "vivid" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sharkdp/vivid/archive/v{{ version }}.tar.gz
  sha256: 325f16df916e4192d56d589839be474801ffd3d6a105f4a1a033221570ff6b56

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - vivid --help

about:
  home: https://github.com/sharkdp/vivid
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: A themeable LS_COLORS generator with a rich filetype datebase
  dev_url: https://github.com/sharkdp/vivid

extra:
  recipe-maintainers:
    - anjos
