{% set name = "vivid" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sharkdp/vivid/archive/v{{ version }}.tar.gz
  sha256: 88db6158dad60aba66ae16f2cd1b09f515625940a33bada65da5562a03538e49

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:

test:
  commands:
    - vivid --help

about:
  home: https://github.com/sharkdp/vivid
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: A themeable LS_COLORS generator with a rich filetype datebase
  dev_url: https://github.com/sharkdp/vivid

extra:
  recipe-maintainers:
    - anjos
